application:
  host: 47.94.230.44

server:
  tomcat:
    basedir: /root/app/tmp/tomcatio/information-manager-system-admin-web

upload:
  fileDirectory: /root/app/files/

project:
  template:
    articleTemplateFilePath: /root/app/information-manager-system/front-end/static/template/InfoTemplate.html
    articleTemplateProduceFileSaveDirectory: /root/app/information-manager-system/front-end/static/article/