application:
  host: 47.94.230.44

server:
  tomcat:
    basedir: /root/app/tmp/tomcatio/information-manager-system-web/

upload:
  fileDirectory: /root/app/files/

project:
  template:
    articleTemplateFilePath: /opt/app/information-manager-system/front-end/static/template/InfoTemplate.html
    articleTemplateProduceFileSaveDirectory: /opt/app/information-manager-system/front-end/static/article/
    bookTemplateFilePath: /opt/app/information-manager-system-web/front-end/static/template/bookTemplate.html
    bookTemplateProduceFileSaveDirectory: /opt/app/information-manager-system-web/front-end/static/