application:
  host: 139.9.125.122

server:
  tomcat:
    basedir: /opt/app/jiaochengshu/information-manager-system-tomcatiotemp/

upload:
  fileDirectory: /opt/app/jiaochengshu/information-manager-system-files/

project:
  template:
    articleTemplateFilePath: /opt/app/jiaochengshu/information-manager-system/front-end/static/template/InfoTemplate.html
    articleTemplateProduceFileSaveDirectory: /opt/app/jiaochengshu/information-manager-system/front-end/static/article/
    bookTemplateFilePath: /opt/app/jiaochengshu/information-manager-system-web/front-end/static/template/bookTemplate.html
    bookTemplateProduceFileSaveDirectory: /opt/app/jiaochengshu/information-manager-system-web/front-end/static/