application:
  host: localhost

server:
  tomcat:
    #长时间不进行上传操作，导致/tmp下面的tomcat临时文件目录被删除，上传文件时获取不到文件目录，导致报错
    basedir: F:\temp\jiaochengshu\tomcat\information-manager-system-web-temp\

upload:
  fileDirectory: F:\temp\jiaochengshu\information-manager-system-files\

spring:
  http:
    multipart:
      # 上传文件的临时目录
      location: F:\temp\jiaochengshu\tomcat\information-manager-system-web-io\

project:
  template:
    articleTemplateFilePath: D:\workspace\githubjava\information-manager-system\information-manager-system-web\src\main\resources\static\template\infoTemplate.html
    articleTemplateProduceFileSaveDirectory: D:\workspace\githubjava\information-manager-system\information-manager-system-web\target\classes\static\article\
    bookTemplateFilePath: D:\workspace\githubjava\information-manager-system\information-manager-system-web\src\main\resources\static\template\bookTemplate.html
    bookTemplateProduceFileSaveDirectory: D:\workspace\githubjava\information-manager-system\information-manager-system-web\target\classes\static\

FileSystem:
  UploadFileUrl: http://121.36.139.115:8080/UploadFile