application:
  host: localhost

server:
  port: 80
  servlet:
    session:
      timeout: 2592000

spring:
  thymeleaf:
    prefix: "classpath:/static/"
    suffix: ".html"
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.9.125.122:3306/jiaochengshu?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: lkmKMH9HDYYYYYBBBH

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xingkaichun.information.model

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

multipart:
  maxRequestSize: 100MB
  maxFileSize: 100MB
