application:
  name: information-manager-system-web

server:
  port: 80
  servlet:
    session:
      timeout: 2592000

spring:
  thymeleaf:
    prefix: "classpath:/static/"
    suffix: ".html"

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xingkaichun.information.model

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

multipart:
  maxRequestSize: 100MB
  maxFileSize: 100MB
