application:
  host: 47.94.230.44

server:
  tomcat:
    basedir: /root/app/tmp/tomcatio/information-manager-system-web/

upload:
  fileDirectory: /root/app/files/

project:
  template:
    articleTemplateFilePath: ###
    articleTemplateProduceFileSaveDirectory: ###
    bookTemplateFilePath: ###
    bookTemplateProduceFileSaveDirectory: ###