application:
  host: localhost

upload:
  fileDirectory: D:\temp\files\

spring:
  http:
    multipart:
      location: D:\temp\tomcat-temp\information-manager-system-web\
#长时间不进行上传操作，导致/tmp下面的tomcat临时文件目录被删除，上传文件时获取不到文件目录，导致报错
server:
  tomcat:
    basedir: F:\tmp\tomcat\information-manager-system-web\

project:
  template:
    articleTemplateFilePath: D:\workspace\githubjava\information-manager-system\information-manager-system-web\src\main\resources\static\template\infoTemplate.html
    articleTemplateProduceFileSaveDirectory: D:\workspace\githubjava\information-manager-system\information-manager-system-web\target\classes\static\article\
    bookTemplateFilePath: D:\workspace\githubjava\information-manager-system\information-manager-system-web\src\main\resources\static\template\bookTemplate.html
    bookTemplateProduceFileSaveDirectory: D:\workspace\githubjava\information-manager-system\information-manager-system-web\target\classes\static\